apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: trjk3wlhk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/trjk3wlhk-java-quarkus-gitops